[versions]
kotlin = "2.1.20"
ksp = "2.1.20-1.0.31"
pluginyml = "0.6.0"
packetevents = "2.10.1"
shadow = "8.3.5"
paper = "1.21.10-R0.1-SNAPSHOT"
autoservice-google = "1.1.1"
autoservice-ksp = "1.2.0"
cloud = "2.0.0"
cloud-paper = "2.0.0-beta.10"
gson = "2.12.1"
netty = "4.2.0.Final"
guava = "33.4.8-jre"
bson = "3.0.2"

[plugins]
pluginyml = { id = "net.minecrell.plugin-yml.paper", version.ref = "pluginyml" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow"}
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

[libraries]
autoservice-google = { module = "com.google.auto.service:auto-service", version.ref="autoservice-google" }
autoservice-ksp = { module = "dev.zacsweers.autoservice:auto-service-ksp", version.ref="autoservice-ksp" }

packetevents-spigot = { module = "com.github.retrooper:packetevents-spigot", version.ref = "packetevents" }
netty = { module = "io.netty:netty-buffer", version.ref = "netty" }
paper = { module = "io.papermc.paper:paper-api", version.ref = "paper" }

cloud-core = { module = "org.incendo:cloud-core", version.ref = "cloud" }
cloud-annotations = { module = "org.incendo:cloud-annotations", version.ref = "cloud" }
cloud-kotlin = { module = "org.incendo:cloud-kotlin-coroutines-annotations", version.ref = "cloud" }
cloud-paper = { module = "org.incendo:cloud-paper", version.ref = "cloud-paper" }

gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
bstats = { module = "org.bstats:bstats-bukkit", version.ref = "bson" }

[bundles]
cloud = ["cloud-core", "cloud-annotations", "cloud-kotlin", "cloud-paper"]